org.gradle.jvmargs=-Xlog:gc*:file=/home/runner/work/Telltale/Telltale/gradle_gc.log -Xmx5g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8  -XX:+UnlockExperimentalVMOptions -XX:+UseCompactObjectHeaders -XX:+UseParallelGC -Dkotlin.daemon.jvm.options=-Xmx5g,Xlog:gc*:file=/home/runner/work/Telltale/Telltale/kotlin_gc.log,Dfile.encoding=UTF-8,XX:+UnlockExperimentalVMOptions,XX:+UseCompactObjectHeaders,XX:+UseParallelGC
android.useAndroidX=true
org.gradle.caching=true
dependency.analysis.compatibility=NONE
org.gradle.unsafe.isolated-projects=true
ksp.project.isolation.enabled=true